# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  weight: 1

# Uncomment the lines below to configure your website in a second language.
ja:
 languageCode: ja
 contentDir: content/ja
 weight: 2
 title: 長沢潤一
 params:
   description: Site description in Japanese...
 menu:
   main:
     - name: 传
       url: '#about'
       weight: 1
